delete from completed_event;
delete from schedule;
delete from cabinet_entry;
delete from document;
delete from medication;
delete from notification;
delete from subscription;
delete from "user";
alter table "user" drop column password;
alter table "user" drop column enabled;
alter table "user" drop column verification_code;
alter table "user" drop column password_reset_code;
alter table "user" drop column admin;
alter table "user" alter column id type varchar(32) using id::varchar;
alter table medication alter column user_id type varchar(32) using user_id::varchar;
alter table document alter column user_id type varchar(32) using user_id::varchar;
alter table cabinet_entry alter column user_id type varchar(32) using user_id::varchar;
alter table notification alter column user_id type varchar(32) using user_id::varchar;
alter table subscription alter column user_id type varchar(32) using user_id::varchar;
alter table completed_event alter column user_id type varchar(32) using user_id::varchar;
alter table schedule alter column user_id type varchar(32) using user_id::varchar;
