version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mediminder
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"